[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x928374"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe3a84e"

[colors.normal]
black = "0x665c54"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe78a4e"

[colors.primary]
background = "0x282828"
foreground = "0xdfbf8e"

[env]
LANG = "en_US.UTF-8"
LC_ALL = "en_US.UTF-8"

[font]
size = 18

[font.bold]
family = "FiraCode Nerd Font Mono Med"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono Med"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

# [[keyboard.bindings]]
# chars = "#"
# key = "Key3"
# mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Shift|Control"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

# [shell]
# args = ["-l", "-c", "/opt/homebrew/bin/tmux attach || /opt/homebrew/bin/tmux new-session -A -s AlacT"]
# program = "/bin/zsh"

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.95
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 140
lines = 38

