[tools]
jq = "latest"
k9s = "latest"
kubectx = "0.9.5"
node = "22"
terraform = "latest"
terraform-lsp = "latest"
yarn = "latest"
yq = "latest"
zig = "latest"
terraform-ls = "latest"
kustomize = "latest"
julia = "latest"
kubectl = "latest"
helm = "latest"
ansible = "10.2.0"
argocd = "2.4.8"
fd = "latest"
gh = "latest"
