[tools]
jq = "1.8.1"
k9s = "0.50.16"
kubectx = "0.9.5"
node = "22"
terraform = "1.14.1"
terraform-lsp = "0.0.12"
yarn = "4.12.0"
yq = "4.49.2"
zig = "0.15.2"
terraform-ls = "0.38.3"
kustomize = "5.8.0"
julia = "1.12.2"
kubectl = "1.34.2"
helm = "4.0.1"
ansible = "10.2.0"
argocd = "3.2.1"
fd = "10.3.0"
gh = "2.83.1"
bitwarden = "2025.11.0"
minikube = "1.37.0"
go = "1.25.5"
gofumpt = "0.7.0"
grpcurl = "1.8.9"
lua = "5.1"
atuin = "18.10.0"
foundry = "1.5.0"
neovim = "0.11.5"
pipx = "1.8.0"
uv = "0.9.16"
op = "2.32.0"
zoxide = "0.9.8"
rust = "1.91.1"
gcloud = "548.0.0"
zellij = "0.43.1"
just = "1.43.1"
terragrunt = "0.95.1"
argo = "3.7.6"
yay = "12.5.7"
